backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "comunidade"
    label: "Comunidade"
    files:
      - file: "comunidade.html"
        label: "Conteúdo da Comunidade"
        name: "comunidade_page"
        fields:
          - label: "Título"
            name: "titulo"
            widget: "string"
          - label: "Subtítulo"
            name: "subtitulo"
            widget: "string"
          - label: "Últimos Avisos"
            name: "avisos"
            widget: "list"
            fields:
              - { label: "Aviso", name: "aviso", widget: "string" }
          - label: "Próximos Confrontos"
            name: "confrontos"
            widget: "list"
            fields:
              - { label: "Confronto", name: "confronto", widget: "string" }
          - label: "Cronograma"
            name: "cronograma"
            widget: "text"
          - label: "Regras do Time"
            name: "regras"
            widget: "text"
          - label: "Política de Advertências"
            name: "advertencias"
            widget: "text"
