backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "comunidade"
    label: "Página Comunidade"
    folder: "content/comunidade"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Últimos Avisos"
        name: "avisos"
        widget: "list"
        fields:
          - { label: "Texto", name: "texto", widget: "string" }
      - label: "Próximos Confrontos"
        name: "confrontos"
        widget: "list"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - {
              label: "Logo do adversário",
              name: "logo",
              widget: "image",
              required: false,
            }
          - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Regras", name: "regras", widget: "markdown" }
      - { label: "Advertências", name: "advertencias", widget: "markdown" }
